#----------------------------------
#
# Whether to activate an internal datapack to add Alex's Caves biomes and blocks to certain tags for better mod compat.
#
applyTagAdjustments = true
#----------------------------------
#
# Whether to activate an internal datapack to remove Spelunkery mod's wall mushrooms from Alex's Caves's Primordial Cave biome due to the mushrooms not having safe generation.
#
applySpelunkeryCompatAdjustments = true
#----------------------------------
#
# Whether to make Underweed, Tree Star, Fiddlehead, and Curly Fern be replaceable by
# another block when right clicking them while holding a block in your hands.
#
replaceableSmallPlants = true
#----------------------------------
#
# Whether to make Guano, Guano Block, and Guano Layer be able to be used as fuel in Furnaces.
#
guanoBurnFuel = true
#----------------------------------
#
# Minimum amount of time that Primative Club can stun a mob.
# Full stun time calculation is (Base Time) + (a random number between 0 and Random Extra Time)
#
#Range: 0 ~ 1000000
primitiveClubBaseStunTime = 150
#----------------------------------
#
# Random amount of extra time that Primative Club can stun a mob.
# Full stun time calculation is (Base Time) + (a random number between 0 and Random Extra Time)
#
#Range: 0 ~ 1000000
primitiveClubRandomExtraStunTime = 150
#----------------------------------
#
# Whether to revert the End Story back to its original form when beating Minecraft.
# Alex's Caves replaces this story with their own. This config puts it back to normal if enabled.
#
restoreEndStory = false
#----------------------------------
#
# If enabled, this config makes the Compendium have all biomes and their info unlocked immediately on log-in.
#
unlockAllCompendiumInfo = false
#----------------------------------
#
# Allows setting overrides for how many arrows to spawn with Dreadbow's rain-like attack.
# Format is the arrow item registry name. Then an equal sign =. And ends with the arrow amount.
# Separate multiple entries with a comma , and whitespace will be ignored.
# Example: "alexscaves:seeking_arrow=5, alexscaves:burrowing_arrow=100"
#
# Otherwise, will default to Alex's Caves original code for determining arrow amount for
# the attack which is 30 arrows for dark colored arrows and 5 arrows for all other arrows.
#
dreadbowArrowRainOverrides = ""
#----------------------------------
#
# How quickly the flight meter will recharge for Subterranodon.
# Putting 2 will recharge twice as fast. Putting 0.5 will halve the recharge rate.
#
#Range: 0.0 ~ 1000.0
subterranodonFlightMeterRechargeSpeed = 1.0
#----------------------------------
#
# How quickly the flight meter will be depleted when flying with Subterranodon.
# Putting 2 will deplete the meter twice as fast. Putting 0.5 will slow the meter's usage rate.
#
#Range: 0.0 ~ 1000.0
subterranodonFlightMeterUsageSpeed = 1.0

["Nuclear Furnace Options"]
	#----------------------------------
	#
	# Multiplies the calculated item smelting time in Nuclear Furnace by this number.
	# Lower number means faster smelting. Higher number means slower.
	#
	#Range: 0.0 ~ 1000000.0
	nuclearFurnaceSmeltingSpeedModifier = 1.0

["Cloak of Darkness Options"]
	#----------------------------------
	#
	# Whether Cloak of Darkness's ability should be usable anywhere. Including in bright light or sunlight.
	#
	AllowedCloakOfDarknessAbilityInLight = false

["Extinction Spear Options"]
	#----------------------------------
	#
	# Damage amount for melee attack with Extinction Spear.
	#
	#Range: 0.0 ~ 10000.0
	extinctionSpearMeleeDamage = 8.0
	#----------------------------------
	#
	# Damage amount for ranged attack with Extinction Spear.
	#
	#Range: 0.0 ~ 10000.0
	extinctionSpearRangedDamage = 10.0

["Raygun Options"]
	#----------------------------------
	#
	# Rate of damage for Raygun normally.
	#
	#Range: 0.0 ~ 1000.0
	raygunNormalDamage = 1.5
	#----------------------------------
	#
	# Rate of damage for Raygun when gamma enchanted.
	#
	#Range: 0.0 ~ 1000.0
	raygunGammaDamage = 2.0

["Mob Attack/Health Options"]
	#Range: 1.0 ~ 1000000.0
	atlatitanMaxHealth = 1700.0
	#Range: 1.0 ~ 1000000.0
	atlatitanAttackDamage = 38.0
	#Range: 0.0 ~ 1000000.0
	atlatitanArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	boundroidMaxHealth = 200.0
	#Range: 1.0 ~ 1000000.0
	boundroidAttackDamage = 25.0
	#Range: 0.0 ~ 1000000.0
	boundroidArmor = 30.0
	#Range: 1.0 ~ 1000000.0
	boundroidWrinchMaxHealth = 120.0
	#Range: 0.0 ~ 1000000.0
	boundroidWrinchArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	brainiacWrinchMaxHealth = 140.0
	#Range: 1.0 ~ 1000000.0
	brainiacAttackDamage = 15.0
	#Range: 0.0 ~ 1000000.0
	brainiacArmor = 18.0
	#Range: 1.0 ~ 1000000.0
	candicornMaxHealth = 160.0
	#Range: 1.0 ~ 1000000.0
	candicornAttackDamage = 16.0
	#Range: 1.0 ~ 1000000.0
	caniacMaxHealth = 238.0
	#Range: 1.0 ~ 1000000.0
	caniacAttackDamage = 12.0
	#Range: 1.0 ~ 1000000.0
	caramelCubeMaxHealth = 14.0
	#Range: 1.0 ~ 1000000.0
	caramelCubeAttackDamage = 12.0
	#Range: 1.0 ~ 1000000.0
	corrodentMaxHealth = 116.0
	#Range: 1.0 ~ 1000000.0
	corrodentAttackDamage = 81.0
	#Range: 0.0 ~ 1000000.0
	corrodentArmor = 2.0
	#Range: 1.0 ~ 1000000.0
	deepOneMaxHealth = 180.0
	#Range: 1.0 ~ 1000000.0
	deepOneAttackDamage = 13.0
	#Range: 0.0 ~ 1000000.0
	deepOneArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	deepOneKnightMaxHealth = 260.0
	#Range: 1.0 ~ 1000000.0
	deepOneKnightAttackDamage = 15.0
	#Range: 0.0 ~ 1000000.0
	deepOneKnightArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	deepOneMageMaxHealth = 280.0
	#Range: 1.0 ~ 1000000.0
	deepOneMageAttackDamage = 14.0
	#Range: 0.0 ~ 1000000.0
	deepOneMageArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	ferrouslimeMaxHealth = 110.0
	#Range: 1.0 ~ 1000000.0
	ferrouslimeAttackDamage = 12.0
	#Range: 0.0 ~ 1000000.0
	ferrouslimeArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	forsakenMaxHealth = 1050.0
	#Range: 1.0 ~ 1000000.0
	forsakenAttackDamage = 30.0
	#Range: 1.0 ~ 1000000.0
	forsakenSonicBoomNormalAttackDamage = 14.0
	#Range: 1.0 ~ 1000000.0
	forsakenSonicBoomWeakTaggedAttackDamage = 145.0
	#Range: 0.0 ~ 1000000.0
	forsakenArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	gammaroachMaxHealth = 114.0
	#Range: 1.0 ~ 1000000.0
	gammaroachAttackDamage = 12.0
	#Range: 0.0 ~ 1000000.0
	gammaroachArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	gingerbreadManMaxHealth = 110.0
	#Range: 1.0 ~ 1000000.0
	gingerbreadManAttackDamage = 12.0
	#Range: 1.0 ~ 1000000.0
	gloomothMaxHealth = 14.0
	#Range: 0.0 ~ 1000000.0
	gloomothArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	gossamerWormMaxHealth = 110.0
	#Range: 0.0 ~ 1000000.0
	gossamerWormArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	grottoceratopsMaxHealth = 250.0
	#Range: 1.0 ~ 1000000.0
	grottoceratopsAttackDamage = 110.0
	#Range: 0.0 ~ 1000000.0
	grottoceratopsArmor = 18.0
	#Range: 1.0 ~ 1000000.0
	gumbeeperMaxHealth = 114.0
	#Range: 1.0 ~ 1000000.0
	gumbeeperAttackDamage = 14.0
	#Range: 0.0 ~ 1000000.0
	gumbeeperArmor = 14.0
	#Range: 1.0 ~ 1000000.0
	gummyBearMaxHealth = 236.0
	#Range: 1.0 ~ 1000000.0
	gummyBearAttackDamage = 14.0
	#Range: 1.0 ~ 1000000.0
	gumWormMaxHealth = 550.0
	#Range: 1.0 ~ 1000000.0
	gumWormAttackDamage = 110.0
	#Range: 0.0 ~ 1000000.0
	gumWormArmor = 19.0
	#Range: 1.0 ~ 1000000.0
	hullbreakerMaxHealth = 1500.0
	#Range: 1.0 ~ 1000000.0
	hullbreakerAttackDamage = 36.0
	#Range: 0.0 ~ 1000000.0
	hullbreakerArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	lanternfishMaxHealth = 12.0
	#Range: 0.0 ~ 1000000.0
	lanternfishArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	licowitchMaxHealth = 140.0
	#Range: 1.0 ~ 1000000.0
	licowitchAttackDamage = 13.0
	#Range: 1.0 ~ 1000000.0
	luxtructosaurusMaxHealth = 2600.0
	#Range: 1.0 ~ 1000000.0
	luxtructosaurusAttackDamage = 42.0
	#Range: 0.0 ~ 1000000.0
	luxtructosaurusArmor = 20.0
	#Range: 1.0 ~ 1000000.0
	luxtructosaurusFireBreathAttackDamage = 12.0
	#Range: 1.0 ~ 1000000.0
	magnetronMaxHealth = 130.0
	#Range: 1.0 ~ 1000000.0
	magnetronAttackDamage = 12.0
	#Range: 0.0 ~ 1000000.0
	magnetronArmor = 16.0
	#Range: 1.0 ~ 1000000.0
	mineGuardianMaxHealth = 120.0
	#Range: 1.0 ~ 1000000.0
	mineGuardianAttackDamage = 4.0
	#Range: 0.0 ~ 1000000.0
	mineGuardianArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	notorMaxHealth = 26.0
	#Range: 0.0 ~ 1000000.0
	notorArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	nucleeperMaxHealth = 230.0
	#Range: 0.0 ~ 1000000.0
	nucleeperArmor = 4.0
	#Range: 1.0 ~ 1000000.0
	radgillMaxHealth = 18.0
	#Range: 0.0 ~ 1000000.0
	radgillArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	raycatMaxHealth = 124.0
	#Range: 1.0 ~ 1000000.0
	raycatAttackDamage = 4.0
	#Range: 0.0 ~ 1000000.0
	raycatArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	relicheirusMaxHealth = 520.0
	#Range: 1.0 ~ 1000000.0
	relicheirusAttackDamage = 32.0
	#Range: 0.0 ~ 1000000.0
	relicheirusArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	seaPigMaxHealth = 18.0
	#Range: 0.0 ~ 1000000.0
	seaPigArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	sweetishFishMaxHealth = 14.0
	#Range: 1.0 ~ 1000000.0
	subterranodonMaxHealth = 20.0
	#Range: 1.0 ~ 1000000.0
	subterranodonAttackDamage = 12.0
	#Range: 0.0 ~ 1000000.0
	subterranodonArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	teletorMaxHealth = 118.0
	#Range: 1.0 ~ 1000000.0
	teletorAttackDamage = 4.0
	#Range: 0.0 ~ 1000000.0
	teletorArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	tremorsaurusMaxHealth = 550.0
	#Range: 1.0 ~ 1000000.0
	tremorsaurusAttackDamage = 34.0
	#Range: 0.0 ~ 1000000.0
	tremorsaurusArmor = 8.0
	#Range: 1.0 ~ 1000000.0
	tremorzillaMaxHealth = 3000.0
	#Range: 0.0 ~ 1000000.0
	tremorzillaArmor = 10.0
	#Range: 1.0 ~ 1000000.0
	tremorzillaWeakStompDamage = 12.0
	#Range: 1.0 ~ 1000000.0
	tremorzillaStrongStompDamage = 30.0
	#Range: 1.0 ~ 1000000.0
	tremorzillaScratchAttackDamage = 40.0
	#Range: 1.0 ~ 1000000.0
	tremorzillaTailAttackDamage = 40.0
	#Range: 1.0 ~ 1000000.0
	tremorzillaBiteAttackDamage = 40.0
	#Range: 1.0 ~ 1000000.0
	tremorzillaBeamAttackDamage = 80.0
	#Range: 0.0 ~ 1000000.0
	tremorzillaHighHealthRecoveryAmount = 2.0
	#Range: 0 ~ 1000000
	tremorzillaHighHealthRecoveryRateInTicks = 100
	#Range: 0.0 ~ 1000000.0
	tremorzillaMediumHealthRecoveryAmount = 3.0
	#Range: 0 ~ 1000000
	tremorzillaMediumHealthRecoveryRateInTicks = 20
	#Range: 0.0 ~ 1000000.0
	tremorzillaLowHealthRecoveryAmount = 5.0
	#Range: 0 ~ 1000000
	tremorzillaLowHealthRecoveryRateInTicks = 10
	#Range: 0.0 ~ 1000000.0
	tremorzillaStepHeight = 1.6
	#NOTE: Turning this off could lead to Tremorzilla getting stuck with pathfinding!!! Do not report to Alex's Caves if you turned this off and the mob gets stuck.
	tremorzillaWalkingBlockGriefing = true
	#Range: 1.0 ~ 1000000.0
	trilocarisMaxHealth = 50.0
	#Range: 1.0 ~ 1000000.0
	trilocarisAttackDamage = 4.0
	#Range: 0.0 ~ 1000000.0
	trilocarisArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	tripodfishMaxHealth = 28.0
	#Range: 0.0 ~ 1000000.0
	tripodfishArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	underzealotMaxHealth = 120.0
	#Range: 1.0 ~ 1000000.0
	underzealotAttackDamage = 14.0
	#Range: 0.0 ~ 1000000.0
	underzealotArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	vallumraptorMaxHealth = 124.0
	#Range: 1.0 ~ 1000000.0
	vallumraptorAttackDamage = 13.0
	#Range: 0.0 ~ 1000000.0
	vallumraptorArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	vesperMaxHealth = 116.0
	#Range: 1.0 ~ 1000000.0
	vesperAttackDamage = 13.0
	#Range: 0.0 ~ 1000000.0
	vesperArmor = 0.0
	#Range: 1.0 ~ 1000000.0
	watcherMaxHealth = 130.0
	#Range: 1.0 ~ 1000000.0
	watcherAttackDamage = 14.0
	#Range: 0.0 ~ 1000000.0
	watcherArmor = 0.0

["INTERNAL MARKERS (DO NOT EDIT)"]
	#Range: 1 ~ 1000000
	configVersion = 1

